name: Quran
description: An app to discover holy Quran.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: any
  path_provider: any
  flutter_launcher_icons: any
  flutter_spinkit: any
  flutter_redux: any
  redux_logging: any
  verbal_expressions: any

flutter:
  uses-material-design: true

  assets:
   - assets/resources/fa_IR.json
   - assets/data/chapters.json
   - assets/images/drawer_background.png
   - assets/images/flexible_space_bar_background.png

  fonts:
   - family: IranSans
     fonts:
      - asset: assets/fonts/iran_sans/regular.ttf
      - asset: assets/fonts/iran_sans/extra_light.ttf
        weight: 200
      - asset: assets/fonts/iran_sans/bold.ttf
        weight: 700

flutter_icons:
  android: true 
  ios: true
  image_path: assets/images/icons/launcher.png