name: quran
description: An app to discover The Holy Quran.
version: 1.0.4+5

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  shared_preferences: 0.5.4+3
  cupertino_icons: 0.1.2
  path_provider: 1.4.0
  flutter_launcher_icons: 0.7.4
  flutter_spinkit: 4.0.0
  flutter_redux: 0.5.3
  redux_logging: 0.3.0
  verbal_expressions: 0.4.0
  flutter_slidable: 0.5.4
  page_transition: 1.1.5
  shimmer: 1.0.1
  kiwi: 0.2.0
  esys_flutter_share: ^1.0.2
  firebase_crashlytics: ^0.1.0+3
  url_launcher: ^5.2.7
  flutter_linkify: ^2.1.0

flutter:
  uses-material-design: true

  assets:
   - assets/resources/fa_IR.json
   - assets/resources/en_US.json
   - assets/data/translators.json
   - assets/data/chapters.json
   - assets/data/chapter_translations.json
   - assets/data/verses.json
   - assets/data/verse_translations.json
   - assets/images/quran_background.png

  fonts:
   - family: IranSans
     fonts:
      - asset: assets/fonts/iran_sans/regular.ttf
      - asset: assets/fonts/iran_sans/extra_light.ttf
        weight: 200
      - asset: assets/fonts/iran_sans/bold.ttf
        weight: 700
   - family: Roboto
     fonts:
      - asset: assets/fonts/roboto/regular.ttf
      - asset: assets/fonts/roboto/light.ttf
        weight: 200
      - asset: assets/fonts/roboto/medium.ttf
        weight: 500
      - asset: assets/fonts/roboto/bold.ttf
        weight: 700
   - family: Nabi
     fonts:
      - asset: assets/fonts/nabi/regular.ttf
   - family: Neirizi
     fonts:
      - asset: assets/fonts/neirizi/regular.ttf
   - family: Taha
     fonts:
      - asset: assets/fonts/taha/regular.ttf

flutter_icons:
  android: true 
  ios: true
  image_path: assets/images/icons/launcher.png