name: Quran
description: An app to discover holy Quran.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #  - assets/images/icons/launcher.png

  fonts:
   - family: IranSans
     fonts:
      - asset: assets/fonts/iran-sans/regular.ttf
      - asset: assets/fonts/iran-sans/extra-light.ttf
        weight: 200
      - asset: assets/fonts/iran-sans/bold.ttf
        weight: 700

flutter_icons:
  android: true 
  ios: true
  image_path: assets/images/icons/launcher.png